### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by osirisinferi** [fralonra/basketball-court#1]
Hi there!

I'm having trouble understanding how to implement your code.. Note, I'm a HUGE NodeJS n00b, like, really really no idea how and what.

I did manage to succesfully create `dist/basketball-court.js` with `yarn`, however, when I add `<script src="basketball-court.min.js"></script>` to a HTML page in the same directory as `basketball-court.js`, nothing happens. And if I try to call `court()`, the browser console errors that the function cannot be found.

I'll probably don't really understand all of this, but can you give a pointer? And perhaps add an example in the README?

**Comment by fralonra** [comment]
Sorry for the late reply.

In short, you should use `basketballCourt` instead of `court` if you use this library via script tag as `basketballCourt` is the name exported by rollup: https://github.com/fralonra/basketball-court/blob/f92a71f1707aa423ff1e3aa86e3da17f8cb40a98/rollup.config.js#L22 

This is a typo in the document, thanks for reporting it! And also thanks for giving it a try, I now have a plan to make some changes to it.
